version: '3.8'

services:
  lidar_odometry:
    build:
      context: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    tty: true
    stdin_open: true # <-- Añade esta línea para mantener la terminal interactiva
    volumes:
      - ../:/home/david/ros2_ws # <-- Corregido para montar el workspace completo
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # - $HOME/.Xauthority:/root/.Xauthority:ro
      - /run/user/1000/gdm/Xauthority:/root/.Xauthority:ro
    shm_size: '16gb'
    network_mode: host
    working_dir: /home/david/ros2_ws
    ipc: host
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]



# ros2 launch tensorrt_yolo tensort_yolo_3P.launch.py &&
